# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-06 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('imgAnuncio', models.CharField(max_length=255)),
                ('urlAnuncio', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('imgArea', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AreaInteres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BolsaDeTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('urlPensum', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('costo', models.FloatField()),
                ('imgCurso', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('imgFrase', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GoalsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=50)),
                ('cursoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Curso')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripion', models.CharField(max_length=255)),
                ('fechaLimite', models.DateField()),
                ('notificacion', models.BooleanField()),
                ('icono', models.CharField(max_length=255)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellido', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=50)),
                ('imgPerfil', models.CharField(max_length=255)),
                ('frasePersonal', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=255)),
                ('urlLinkedin', models.CharField(max_length=255)),
                ('urlCurriculum', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('areaEspecializacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Area')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=50)),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsaDeTrabajoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BolsaDeTrabajo')),
                ('usuarioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='cursoprofesor',
            name='profesorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profesor'),
        ),
    ]
