# Generated by Django 2.0.7 on 2018-08-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180729_2237'),
        ('api', '0003_auto_20180730_0141'),
    ]

    operations = [
    ]
